version: "3.8"
services:
  steelbooksatbestbuy_bot:
    env_file: steelbooksatbestbuy_dockerized.env
    build:
      context: .
      dockerfile: steelbooksatbestbuy-bot/Dockerfile
    volumes:
      - ./sqlite_db:/src/sqlite_db
    container_name: steelbooksatbestbuy_bot
    networks:
      - steelbooksatbestbuy_network
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
  steelbooksatbestbuy_website:
    env_file: steelbooksatbestbuy_dockerized.env
    build:
      context: .
      dockerfile:  steelbooksatbestbuy_website/Dockerfile
    volumes:
      - ./sqlite_db:/src/sqlite_db
    container_name: steelbooksatbestbuy_website
    networks:
      - steelbooksatbestbuy_network
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t
  steelbooksatbestbuy_poll_bestbuy:
    env_file: steelbooksatbestbuy_dockerized.env
    build:
      context: .
      dockerfile:  steelbooksatbestbuy_poll_bestbuy/Dockerfile
    volumes:
      - ./sqlite_db:/src/sqlite_db
    container_name: steelbooksatbestbuy_poll_bestbuy
    networks:
      - steelbooksatbestbuy_network
#    stdin_open: true # docker run -i
#    tty: true        # docker run -t

networks:
  steelbooksatbestbuy_network:
    external: true