# Generated by Django 4.0.4 on 2022-06-20 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_search_string', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild_id', models.IntegerField(unique=True)),
                ('guild_name', models.CharField(max_length=300)),
                ('channel_id', models.IntegerField(unique=True)),
                ('channel_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('product_url', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
                ('archived', models.BooleanField(default=False)),
                ('sku', models.CharField(max_length=300, unique=True)),
                ('needs_to_be_processed_by_bot', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.IntegerField()),
                ('email', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('phone_number', models.IntegerField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleToTargetForGuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_to_tag_name', models.CharField(max_length=500)),
                ('role_to_tag_id', models.IntegerField()),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelbooksatbestbuy.guild')),
            ],
        ),
        migrations.CreateModel(
            name='QuantityUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('regular_price', models.FloatField()),
                ('sales_price', models.FloatField()),
                ('sales_channel_exclusivity', models.CharField(max_length=300)),
                ('purchaseable_via_pickup', models.BooleanField()),
                ('status_for_pickup', models.CharField(max_length=300)),
                ('purchaseable_via_shipping', models.BooleanField()),
                ('status_for_shipping', models.CharField(max_length=300)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelbooksatbestbuy.media')),
            ],
        ),
        migrations.CreateModel(
            name='LastTimeAlertWasUsedForSpecificMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_for_updates_to_ignore', models.DateTimeField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelbooksatbestbuy.alert')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelbooksatbestbuy.media')),
            ],
        ),
        migrations.AddField(
            model_name='alert',
            name='person_to_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='steelbooksatbestbuy.user'),
        ),
    ]
