# Generated by Django 4.0.4 on 2022-12-09 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steelbooksatbestbuy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lasttimealertwasusedforspecificmedia',
            name='alert',
        ),
        migrations.RemoveField(
            model_name='lasttimealertwasusedforspecificmedia',
            name='media',
        ),
        migrations.RemoveField(
            model_name='roletotargetforguild',
            name='guild',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.DeleteModel(
            name='LastTimeAlertWasUsedForSpecificMedia',
        ),
        migrations.DeleteModel(
            name='RoleToTargetForGuild',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
