# Generated by Django 4.0.4 on 2023-05-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steelbooksatbestbuy', '0002_remove_lasttimealertwasusedforspecificmedia_alert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityupdate',
            name='attributes_changed',
            field=models.CharField(default=None, max_length=5000, null=True),
        ),
    ]
